project_id = "abssbmealjdjbyzcresj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
api_port = 54326
smtp_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
additional_redirect_urls = ["https://abssbmealjdjbyzcresj.supabase.co/auth/v1/callback"]
api_external_url = "http://127.0.0.1:54321"
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = true
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"

[edge_functions]
enabled = true
port = 54329
inspector_port = 54330